services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "9001:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://server:9002
    volumes:
      - ./public:/app/public
      - ./src:/app/src

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9002:9002"
    environment:
      - PORT=9002
      - NODE_ENV=production
      - JWT_SECRET=your_jwt_secret_key_here
      - MONGO_URI=mongodb://mongodb:27017/olympus-hero
    volumes:
      - ./server:/app/server
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=olympus-hero

volumes:
  hero-data: 
  mongodb-data: 