services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "9001:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://server:9002
    volumes:
      - ./public:/app/public
      - ./src:/app/src


  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=9002
      - JWT_SECRET=dev_jwt_secret
      - MONGO_URI=mongodb://mongodb:27017/olympus-hero
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./:/app
      - /app/node_modules
      - ./storage/:/app/storage
    ports:
      - "9002:9002"
    command: npm run server:dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data-dev:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=olympus-hero

volumes:
  hero-data: 
  mongodb-data: 